const ilanlarVerisi = [
    {
        "id": 1783715695131,
        "baslik": "deneme3",
        "durum": "kat-karsiligi",
        "tip": "",
        "konutTipi": "",
        "konutSekli": "",
        "il": "",
        "ilce": "",
        "mahalle": "",
        "fiyat": "",
        "paraBirimi": "",
        "aciklama": "",
        "koor": "34.009092, 38.369623",
        "klasorIsmi": "",
        "resimler": [],
        "videoUrl": "",
        "İlan Tarihi": "",
        "M²": "",
        "Ada": "",
        "Parsel": "",
        "Oda Sayısı": "",
        "Bina Yaşı": "",
        "Bulunduğu Kat": "",
        "Kat Sayısı": "",
        "Isıtma": "",
        "Eşyalı mı?": "",
        "Kullanım Durumu": "",
        "Site İçerisinde?": ""
    }
];