const ilanlarVerisi = [
    {
        "id": 1783707728193,
        "baslik": "Deneme ",
        "durum": "satilik",
        "tip": "",
        "konutTipi": "",
        "konutSekli": "",
        "il": "",
        "ilce": "",
        "mahalle": "",
        "fiyat": "",
        "paraBirimi": "",
        "aciklama": "",
        "koor": "34.008792, 38.369878",
        "klasorIsmi": "",
        "resimler": [],
        "videoUrl": "",
        "İlan Tarihi": "",
        "M²": "",
        "Ada": "",
        "Parsel": "",
        "Oda Sayısı": "",
        "Bina Yaşı": "",
        "Bulunduğu Kat": "",
        "Kat Sayısı": "",
        "Isıtma": "",
        "Eşyalı mı?": "",
        "Kullanım Durumu": "",
        "Site İçerisinde?": ""
    },
    {
        "id": 1783709122017,
        "baslik": "deneme2",
        "durum": "kiralik",
        "tip": "Konut",
        "konutTipi": "Apartman Dairesi",
        "konutSekli": "Daire",
        "il": "",
        "ilce": "",
        "mahalle": "",
        "fiyat": "",
        "paraBirimi": "",
        "aciklama": "",
        "koor": "34.009210, 38.369581",
        "klasorIsmi": "",
        "resimler": [],
        "videoUrl": "",
        "İlan Tarihi": "",
        "M²": "",
        "Ada": "",
        "Parsel": "",
        "Oda Sayısı": "",
        "Bina Yaşı": "",
        "Bulunduğu Kat": "",
        "Kat Sayısı": "",
        "Isıtma": "",
        "Eşyalı mı?": "",
        "Kullanım Durumu": "",
        "Site İçerisinde?": ""
    }
];